site_name: study
use_directory_urls: false

nav:
  - Home: index.md
  - LINUC2: 
    - index: linuc2/index.md
    - dnsの基本: 
      - 基本: linuc2/dns.md
      - zoneファイル: linuc2/zone.md
      - セキュリティ: linuc2/security.md
    - Webサーバー:
      - Apache: linuc2/apache.md
      - Nginx: linuc2/nginx.md
    - Mail:
      - mail: linuc2/postfix.md
    - Samba|NFS:
      - Samba: linuc2/samba.md
      - NFS: linuc2/nfs.md
    - セキュリティ:
      - netfilter/iptables: linuc2/iptables.md
      - ssh: linuc2/ssh.md
      - vpn: linuc2/vpn.md


not_in_nav: |
  /notinclude.md

theme:
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    # - navigation.footer
  name: material
  palette:
    primary: white
  language: ja
  font:
    text: Noto Sans JP
    code: Inconsolata

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format